### ISSUE TITLE
[Feature Request] Mob Farm upgrade should be stackable

### ISSUE THREAD

**Issue by SkyRunner55** [MarkusBordihn/BOs-Easy-Mob-Farm#100]
Since the rework of the mob farm, with cards, upgrades, and so on, moving a mob farm around has been pretty tough. 

Before the rework, it was just the mob farm, a lasso/egg, and a sword.
Now, you can fill your inventory very quickly since the upgrades can't be stacked, and it's very annoying.

![2024-12-15_17 23 44](https://github.com/user-attachments/assets/1d914b8e-634d-419a-b8d7-90a12cb90b66)

I see some solutions:
1) The first obvious solution is to make the upgrades stackable, there will not be stackable inside the mob farm however.
2) When breaking a mob farm, all upgrades, filters, and card/mob catcher should be kept inside, but the mob loot should not and will drop to the ground

I'am currently using the 1.21.1 version

**Comment by Ynaught** [comment]
Same with cards of the same type and rarity. Carrying 3 common zombie cards are a bit. . . annoying. Even if they are stackable but unique so that they can't share an inventory space, it would allow them to go inside a bundle, which would be very nice.

**Comment by SkyRunner55** [comment]
> Same with cards of the same type and rarity. Carrying 3 common zombie cards are a bit. . . annoying. Even if they are stackable but unique so that they can't share an inventory space, it would allow them to go inside a bundle, which would be very nice.

I forgot about that

**Comment by MarkusBordihn** [comment]
Thank you for your feedback! Here’s an improved plan to address the issues you mentioned:

# Stacking Enhancements

There was an issue in version 1.21.4 where auto-moving items to the correct slot when stacked did not work properly. I'll investigate this and work on resolving it.
Once this issue is fixed, I’ll explore adding stacking for enhancements wherever possible. However, these will remain non-stackable inside the mob farm itself to preserve functionality.

# Storing Items When Breaking the Mob Farm

Storing enhancements, filters, and other upgrades in the mob farm when it’s broken will work as expected.
Unfortunately, storing the mob capture card or mob capture item directly in the farm is limited by technical restrictions in the latest game versions. This is due to constraints on storing complex item metadata within a block's NBT.

# Stacking Mob Capture Cards

While mob capture cards could technically be stackable, in practice this is highly challenging. Each mob can carry unique metadata, such as equipment, loot modifiers, or other attributes, which are stored in the capture card.
Items in Minecraft can only stack if they are exactly identical, including all stored metadata. For instance, one zombie card may drop loot while another doesn’t because of differences in these metadata.

# Improvements for Capture Card Stacking

I’ll explore filtering unnecessary metadata (e.g., attributes that don’t impact functionality) to make mob capture cards more likely to stack. 
However, it’s expected that some cards may still remain unstackable due to differences in loot modifiers or other key data.

# Mob Capture Card Storage Binder

Additionally, I working on a Mob Capture Card Storage Binder, which is able to keep all of your cards in a single slot.

Thank you again for highlighting these points. I’ll do my best to strike a balance between usability and the technical limitations of the game!

**Comment by Ynaught** [comment]
> # Storing Items When Breaking the Mob Farm
> Storing enhancements, filters, and other upgrades in the mob farm when it’s broken will work as expected. Unfortunately, storing the mob capture card or mob capture item directly in the farm is limited by technical restrictions in the latest game versions. This is due to constraints on storing complex item metadata within a block's NBT.

I'd also like to address that placing a mob farm template down in the world makes you lose it as breaking it to pick it back up does not drop anything/return the item. This is probably just a bug/oversight when making the loot tables. I've only tested it with the tier 2 template.

 
> # Stacking Mob Capture Cards
> While mob capture cards could technically be stackable, in practice this is highly challenging. Each mob can carry unique metadata, such as equipment, loot modifiers, or other attributes, which are stored in the capture card. Items in Minecraft can only stack if they are exactly identical, including all stored metadata. For instance, one zombie card may drop loot while another doesn’t because of differences in these metadata.

That's fine. Even if every card is unique, just making them stackable would still allow us to stack them in vanilla bundle item, even if not in a direct inventory slot.

> # Mob Capture Card Storage Binder
> Additionally, I working on a Mob Capture Card Storage Binder, which is able to keep all of your cards in a single slot.

This is awesome! ^u^
I love the idea of a collectors book. Bonus points if we can put them in a lectern.

**Comment by SkyRunner55** [comment]
mob farm booster :p
