### ISSUE TITLE
Not dropping mod/datapack-added drops to mods

### ISSUE THREAD

**Issue by jlaine3333** [MarkusBordihn/BOs-Easy-Mob-Farm#11]
**Describe the bug**
Certain items mods add, such as UselessSword's guardian spikes, won't drop when in the farm. They have a high drop rate but no matter how long I let the farm run with any mob, these drops won't spawn. Tangentially related, I also haven't noticed any of the 10 farms I set up for wither skeletons actually drop a single skull.

**To Reproduce**
1. Get a mod that adds drops to a mob (e.g. UselessSword)
2. Capture the mob and put it in a farm (Config the farm to run as fast as possible for ease of testing)
3. Wait. It will only produce vanilla drops

**Expected behavior**
It should drop the additional drops mods add.

**Comment by MarkusBordihn** [comment]
Thanks a lot for the feedback. Unfortunately this is an issue with the Useless Sword's mod itself.
The mod is not defining any loot tables and is using events like "LivingDeathEvent" instead to drop the loot.

This could be only fixed by the Useless Sword's author by defining the correct loot tables like:
https://minecraft.fandom.com/wiki/Loot_table

The issue with the wither skeleton is expected, because their loot tables defines that the skull will only drop if a player has killed the wither skeleton. 
This means you are not able to build any auto farm which could farm wither skeleton skulls without any player interaction. 
For this reason the mob farm is also not able to drop any wither skeleton skulls without overwriting the loot table itself.

I could add a config switch for the wither skeleton skull (disabled by default), but I would not recommend this on any multiplayer server, because it would be overpowered.
