### ISSUE TITLE
[Crash Report] Server crashes on picking up cards

### ISSUE THREAD

**Issue by MeetTheCatThe** [MarkusBordihn/BOs-Easy-Mob-Farm#110]
💡 Check the
[Bug Tracker](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/issues?q=label%3Abug) and [Crash Tracker](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/issues?q=label%3Acrash) before reporting a new crash.
There you can find a lot of useful information and solutions for common problems.

**Note**:
Please make sure to fill out the following template to the best of your ability. This will help us
diagnose and resolve the issue faster. Without the necessary logs, there might not be much we can do
to help.

**Minecraft and Mod version** 🐞
I am using Minecraft 1.21.4 with Mod version 8.9.1

**Description of the crash** 💥
I installed the mod, and everything seemed to be working fine at first. My girlfriend started fishing because I told her about the mod and that you can fish for the cards used for farms. Suddenly, the server crashed. Neither of us knew why. The server restarted normally but crashed again whenever either of us tried to reconnect. I removed the mod from the server, and everything ran smoothly. So, I reloaded the mod onto the server, and everything was fine again. Later that night, I went out to kill some mobs to get cards for a farm. A card dropped, and I saw it just before the server crashed again. The server restarted normally but crashed again as soon as we tried to reconnect. I then removed the mod again and configured it so that cards wouldn't drop. This seemed to work fine without the cards. However, as soon as cards drop again (or this setting is re-enabled), the server crashes, and the game becomes unplayable because the server restarts every time someone tries to reconnect.

**Steps to reproduce the crash** ⚙️

1. Fishing or slaying mobs - no matter what mob
2.
3.

**Expected behavior before the crash** ✔️
I salyed mobs for cards and I was fishing for them in expectation to get cards for the farm

**Logs** 📝
To speed up the diagnosis, please provide the following files if possible:

- [logs/debug.log](https://mclo.gs/elmNNpa)
- [logs/latest.log](https://mclo.gs/HWXtAXq)
- [crash-reports/crash-...txt](https://mclo.gs/xBzGPci)

These logs contain essential details that will help me identify the problem and offer more accurate
assistance.
You can upload the logs to https://gist.github.com/ or https://mclo.gs/ and share the link here.

**Additional context** 📋
Mod was loaded via Modrinth-Modloader. Another problem the mod brings in is, that now items of the same type won't stack anymore automaticly

**Comment by MarkusBordihn** [comment]
Thank you for the detailed report.  

The crash logs suggest that the issue is likely caused by a version mismatch between the mod and the server. 
This typically occurs when the mod version doesn't align with the Minecraft server version (e.g., using a mod for Minecraft 1.21.x on a 1.21.4 server).  

**Error Details:**  
```
java.lang.NoClassDefFoundError: net/minecraft/class_638
    at knot//de.markusbordihn.easymobfarm.item.mobcapturecard.MobCaptureCardItem.method_7864(MobCaptureCardItem.java:122)
```
The error points to the `getName` function of the item, indicating a missing class or reference. 
This further reinforces the likelihood of a version mismatch between the server and the mod.

**Version Check:** 
   - Verify that the Minecraft server, Fabric, Fabric Loader, and the Easy Mob Farm mod are all updated to compatible versions.  
   - Ensure that the mod version specifically matches the Minecraft server version (e.g., both are 1.21.4).

**Reinstallation:**  
   - If the versions are correct but the issue persists, try reinstalling the mod to rule out corrupted files.  
   - Fully delete and re-download the mod from a trusted source, ensuring it is the latest compatible version.

If the issue continues even after updating, I’ll attempt to reproduce the error on one of my test servers to investigate further.

**Comment by MeetTheCatThe** [comment]
Thank you for responding. 
As said in the opening post, the serverversion is on Minecraft 1.21.4 - Fabric Loader Verion 0.16.9 - Fabric Installer Verion 1.0.1 - if that helps. But I am sure you can get more information out of the logs.
What I've done is to create a new Fabric instance vie Modrinth and add mods via "Add content..." whats is "+ install content" since the last update. So Modrinth sets the filter to "Fabric" and "Minecraft 1.21.4". That's why I'm wondering it does not work - for all other mods it worked fine. So I thought this is the same.  

What I did so far: 
- I controlled, that Minecraft, Fabric and mod version match (Minecraft 1.21.4, Fabric Loader 0.16.9, Easy Mob Farm 8.9.1)
- I uninstalled the Verion, downloaded it again (from modrinth - I guess this counts as a trusted source) and uploaded it again
- Same problems again

In between I downgraded to version 8.9.0 just for testing. Same problem here. 
Well I am just a simple mineraft player who loves to install mod from ppl that are making the game better in a way I like, I have no idea of troubleshooting things tbh. When something goes wrong I skip the mod or searching for an alternative. This time I thought I create a ticket because that mod caught me and i thought maybe my problem is not only my problem.

So thank you for looking into this mate. If I can provide any further info for solving let me know - I try it all if needed.

best regards and marry christmas

**Comment by MarkusBordihn** [comment]
Thank you so much for the detailed feedback. 
I appreciate the effort you put into troubleshooting this.

Although I wasn’t able to reproduce the issue directly, one of the players on my test server managed to trigger a similar problem.

I’ve implemented a fix, and it should be available in version 8.9.2 and later. 
This update should be ready in the next few minutes on Modrinth and CurseForge.

Please let me know if this resolves the issue for you, or if you encounter any further crashes or errors. 
Your feedback is invaluable in ensuring the stability of the mod.

Happy Holidays!

**Comment by MeetTheCatThe** [comment]
Hey,
I just had the possibillity to test the new version and crad dropping seems to work fine so far. They can drop and they can be picked up. Thank you very much for fixing it that fast! 
One Problem stays. As you can see in the screenshot items are not stacking anymore even if they are the same type. Thas since I installed the mod and is gone, when I remove it from the server. Any suggestions why this happens?

Again thank you so far! Amazing work
![Screenshot](https://github.com/user-attachments/assets/527918bc-249d-4e4e-b3b3-113f413ac07b)

Providing further informations:
First, I spawned cows using a spawn egg to check if it works—specifically, to see if cards drop and the server doesn't crash. That worked fine. However, as seen in the screenshot, the server started creating more and more item stacks, even though they should normally stack automatically. So, later at night, I went out again to fight some mobs, mostly spiders. I usually had 2-3 thread stacks in my inventory. Sometimes I can combine the stacks, but other times I can’t, even if they’re the same items. This behavior has only occurred since I installed the mod, which I find a bit puzzling.
I tested a bit further and farm have the same problem - wheat or carrots that I harvest are making mor stacks wich are stackable together but not stacking when i collect them.

**Comment by MarkusBordihn** [comment]
Thank you for the confirmation! 😊  

The behavior you're describing is actually **intentional by design.** 
Each mob can carry unique metadata, such as equipment, loot modifiers, or other attributes, which are stored within the capture card. 
This ensures that mobs retain their individuality and prevents all mobs from generating identical loot.  

For more details, you can refer to this discussion:  
🔗 [GitHub Issue #100 - Comment](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/issues/100#issuecomment-2546327882)

I’ve already implemented a clean-up process to remove unnecessary metadata, making it more likely for items to stack. 
However, in some cases, it's unavoidable when mobs have distinct data.  

### **How to Verify:**  
You can verify the metadata by running the following command while holding the mob capture card:  
```
/data get entity @s SelectedItem
```  
This will display all stored metadata. If **any** part of the data differs (even slightly), the items will not stack.  

![image](https://github.com/user-attachments/assets/29ba2b62-23ef-4b28-9ed5-4c748ee94f3d)

### **Next Steps:**  
If you encounter specific cases, feel free to share examples. 
I’d be happy to review the metadata and explore whether further clean-up can improve stacking without compromising important attributes.  

I'm glad to hear the fix for the card drops is working well! 🎮

**Comment by MeetTheCatThe** [comment]
Thank you for the explanation. I checked with the command and noticed that for rotten flesh and strings, the stack sometimes includes the original mob (like zombie or spider), and there’s another variant where it says skeleton. Is that intentional? I haven’t checked yet if I can actually get rotten flesh or strings from skeletons, but if I interpret the metadata correctly (with my limited knowledge), it seems like that’s the case.

I also noticed that for almost every new item, I get a new stack in the inventory. However, I can sometimes merge these into one stack afterward. Is this also intentional? It doesn’t seem like it, but maybe I’m mistaken. If it would help, I could make a short video for better understanding if anything is unclear.

![Screenshot 2024-12-25 145140](https://github.com/user-attachments/assets/9014bece-42d6-4f27-a55c-73efb55f2327)
