### ISSUE TITLE
[Mod Support] Easy Mob Farm, Spider catching issue

### ISSUE THREAD

**Issue by mal211** [MarkusBordihn/BOs-Easy-Mob-Farm#13]
https://www.curseforge.com/minecraft/mc-mods/easy-mob-farm

For some reason, the spider Mob is not catchable with a small urn. 

Also, on a side note, curseforge is being weird with the latest version of this mod, it think the version released in august is the most up to date version, not the one released in October.  I had the spider catching issue in both versions. 

![image](https://user-images.githubusercontent.com/116613714/197669045-961ac969-84ef-4694-88cc-fe5872fc22d9.png)
![image](https://user-images.githubusercontent.com/116613714/197669105-ab104ada-8218-43fe-8633-d8896c1c7683.png)
![image](https://user-images.githubusercontent.com/116613714/197669163-3b2c1175-ed66-43fe-bf62-68b881bcf2ec.png)

### Animal / Monster
**Hostile Monster**
-minecraft:spider

**Comment by MarkusBordihn** [comment]
I assume that the spider entry is missing in your config file.

![image](https://user-images.githubusercontent.com/12183293/197832295-71c963df-a3fe-40a2-83cb-5f62095a5901.png)

I adjusted the config file in the latest version, so the easiest way would be to delete the existing config so that the new config get's automatically created by the next start.

If this is still not working, please attach your config file here, so that I could take another look. Thanks

**Comment by mal211** [comment]
> I assume that the spider entry is missing in your config file.
> 
> ![image](https://user-images.githubusercontent.com/12183293/197832295-71c963df-a3fe-40a2-83cb-5f62095a5901.png)
> 
> I adjusted the config file in the latest version, so the easiest way would be to delete the existing config so that the new config get's automatically created by the next start.
> 
> If this is still not working, please attach your config file here, so that I could take another look. Thanks

I deleted the config, but I'm still having the same issue.
I tried to attach it, but it says it doesn't support that file type.

![image](https://user-images.githubusercontent.com/116613714/197897190-c5bf2309-3209-4216-8a9c-280a9ef7dcac.png)
