### ISSUE TITLE
Coloured wool not dropping

### ISSUE THREAD

**Issue by Jaheira12** [MarkusBordihn/BOs-Easy-Mob-Farm#16]
I have several plains farms running with white sheep and a number with different coloured sheep.
The white sheep are dropping wool as expected. But am receiving no wool at all from the coloured sheep.
both farms are dropping raw mutton as expected. Including a sword in one of the farms made no difference.

**Comment by MarkusBordihn** [comment]
Sorry but unfortunately I'm not able to reproduce the issue on my side.

![image](https://user-images.githubusercontent.com/12183293/224780718-704f1452-0d54-471a-8be9-c0c6c14521ae.png)

Could you please provide additional details to be able to reproduce the issue.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Debugging**
Before reporting a issue please check if there is anything relevant in the crash-reports, debug.log and latest.log file.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**

**Additional context**
Add any other context about the problem here.

**Comment by Jaheira12** [comment]
I can't provide steps to reproduce - the farms are operating just not producing any wool (white sheep farms are working as expected)
It may be a mod issue, see list below and find latest log file attached:
Advanced Netherite
Architectury API (Fabric/Forge)
Ars Elemental
Ars Instrumentum
Ars Nouveau
Artifacts
AutoRegLib
Awesome Dungeon - Forge
Awesome Dungeon Ocean edition - Forge
Balm (Forge Edition)
Better Fps - Render Distance[Forge]
Biomes O' Plenty
BlockUI
Bookshelf
Botany Pots
Botany Pots Tiers
Botany Trees
Caelus API (Forge)
Chunk-Pregenerator
Clean Cut
Collective
Comforts (Fabric/Forge/Quilt)
Configured
Connectivity[Forge/Fabric]
Cooking for Blockheads
Corail Tombstone
Corail Woodcutter
Crafting Tweaks
CreativeCore
Croptopia
Cucumber Library
Curios API (Forge)
Cyclops Core
Domum Ornamentum
Dungeon Crawl
Dynamic View[Forge]
Easy Mob Farm
Easy Piglins
Easy Villagers
Elytra Slot (Forge)
FallingTree (Forge&Fabric)
Farsight [Forge]
Fast Leaf Decay
FTB Chunks (Forge)
FTB Essentials (Forge)
FTB Library (Forge)
FTB Ultimine (Forge)
Glassential
Global Packs
Goblin Traders
Health Overlay (Forge)
Iron Chests
Jade
JourneyMap
JourneyMap Integration
Just Enough Items (JEI)
Just Enough Resources (JER)
Library Ferret - Forge
Material Elements
McJtyLib
MineColonies
Mob Grinding Utils
Moonlight Lib
Mouse Tweaks
Multi-Piston
Mystical Agradditions
Mystical Agriculture
Natures Compass
OpenBlocks Elevator
Packing Tape
Patchouli
Pipez
Productive Bees
Pylons
Quark
RFTools Base
RFTools Builder
RFTools Control
RFTools Power
RFTools Storage
RFTools Utility
Simple Magnets
Simple Storage Network
Sophisticated Backpacks
Sophisticated Core
Spice of Life: Carrot Edition
Storage Drawers
Storage Racks
Structurize
SuperMartijn642's Config Lib
SuperMartijn642's Core Lib
TerraBlender (Forge)
Torchmaster
Trash Cans
Waystones
When Dungeons Arise - Forge!
[latest.log](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/files/10961663/latest.log)

**Comment by MarkusBordihn** [comment]
Thanks for the feedback I will test some mod combinations, but at the moment I see nothing suspicious. 🤔

**Comment by Jaheira12** [comment]
I think I found the issue - I had sheered the sheep before picking it up - I released the sheep allowed the wool to regrow and recaught the sheep and the issue was resolved

**Comment by MarkusBordihn** [comment]
Thanks a lot for the feedback. Seems reasonable that the data entries for the colors are removed once the sheep is sheered. 🤔
I will check if there are any other additional data entries, I could use for sheered sheep.

**Comment by Jaheira12** [comment]
maybe just a sheered/shorn sheep in the farm ;)

Then its a feature not a bug ;) if you don't want wool from your farm

**Comment by MarkusBordihn** [comment]
I updated the farms so that they are showing if a sheep is sheared.
