### ISSUE TITLE
No drop from magma Cube

### ISSUE THREAD

**Issue by chipie23** [MarkusBordihn/BOs-Easy-Mob-Farm#18]
**Describe the bug**
Hi, we got a nether farm, and place a magma cube (both big size and tiny one) inside with netherite lead from mob catcher, the farm is "wortking", but there is no drop, it give xp bottle, we also tried with and without a sword (looting 3) and for several hours, is there something special we need to do to obtain the drop ?

**Additional context**
the other farm works, we have a panda in a diamond lead in a jungle farm and an enderman in a bottle also

Thank you

**Comment by MarkusBordihn** [comment]
Thanks for the report. I performed some test and this is working as expected.
You need to capture a big magma cube, smaller ones are not working.

Because there is only a 25% drop change it could be it take some time before it is dropping Magma Cream.
As soon you captured such a magma cube, it will drop even without a sword, but at a lower drop rate.

![image](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/12183293/5c40cf7e-6c46-4837-9b81-6c176140102b)
