### ISSUE TITLE
Integration with Refined Storage Mod

### ISSUE THREAD

**Issue by colbycanutt** [MarkusBordihn/BOs-Easy-Mob-Farm#27]
Using Minecraft 1.20.1, Forge 47.1.1 and Easy Mob Farm easy_mob_farm_1.20.1-6.3.0.jar

Would like to be able to connect an Importer from Refined Storage to the back of the Mob farm to have dropped items and XP bottles imported into the Refined Storage Computer.

Currently, to integrate with Refined Storage I have the Mob farm sitting on top of a hopper dropping into a chest/barrel that the Importer can pull from.  While this works, it does not collect the full XP bottles.

**Comment by MarkusBordihn** [comment]
Thanks for your feedback. The "Importer" from Refined Storage should work fine on the bottom, so there should be no need to use a chest/barrel between the importer and the mob farm.

![image](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/12183293/fb16ec43-ca50-4660-abc4-0197d94b688a)

One question about the XP bottles, at the moment they are not fetchable using a hopper or so, because you need at least one empty bottle / xp bottle in the farm to collect the xp.

If the farm should eject all xp bottles, you would need to have a way to import them.
Normally you are using the back for importing items and using the bottom to exporting item (like the furnace).

In the case I enable the back for exporting items, you would not be able to importing items from the same side.
It would be great if you could clarify your expected workflow with "importing" and "exporting" more in detail, so see what I could do in this case.

**Comment by x-j0nnay-x** [comment]
Could we check to see what item is being inserted into the side? Then if it returns bottle it imports to bottle slot? 

For exporting we can check to see if the stack size is grater than 1. If it returns true move all but 1 to output slot if output slots have room, or allow extraction from side bottom if returned true

Also could add a block state called collect XP. Once give an empty bottle can turn true.
This will then consume the bottle. Letting it collect xp and the we just allow export of items in slot from bottom,

**Comment by MarkusBordihn** [comment]
The version 1.20.1 is now supporting exporting of items over the bottom and importing over the back.
If you want to export experience bottles, you need to import glass bottles to have a Infinity xp farm.

@x-j0nnay-x 
I tough about exporting everything greater than 1 as well, but it would be too overpowered if you don't need to supply any bottles and get out a infinity numbers of experience bottles without any additional work.

**Comment by x-j0nnay-x** [comment]
@MarkusBordihn yeah it would be, with laser IO you can configure the extraction to take all but one anyways. So adding the ability to extract does the same thing as long as you use the right mod. But I do agree fully with it being overpowered.
