### ISSUE TITLE
Enderman just dropping Chorus Fruits

### ISSUE THREAD

**Issue by Flederviech** [MarkusBordihn/BOs-Easy-Mob-Farm#36]
We are currently testing my modpack (200+ mods) for a buildingserver. And it seems like enderman are dropping just chorus fruits and no perls. I couldn´t find any option in the config file.  And it´s not a generell Problem ... outside the Farm they are dropping Perls. 
Minecraftversion is 1.20.1 with Forge 47.0.46 with your Modversion on 6.6.1 
If you need more information,please let me know. 
I would really appreciate your help :) Thank you.

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report. The mod is using the standard loot tables from the game to define the corresponding drops.
With my reference mod pack, this works fine and Enderman dropping Ender Pearls (nothing else).
![image](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/12183293/1e69ffe2-94bd-405d-acd1-1bbc6457767b)

The standard loot table for Enderman looks like:
![image](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/12183293/ef5dae7d-e30e-4f99-8849-59afb7f9845e)

As you could see there is no "chorus fruits" in this loot table.
So I assume that one of your mods adjusting the loot tables to make sure that Ender Pearls could only obtain with "real" player kills, but not with mob farms or "pseudo" player.

I will add a config switch to force dropping Ender pearls in such cases, but it could be that the mod has a good reason for this to keep a good game balance or so.

I recommend that you check which mod is adjusting the loot tables to see if this is by design or maybe an error to make sure that your mod pack is well balanced.

**Comment by MarkusBordihn** [comment]
The config switch is added in 6.6.2 and is called `endermanDropEnderPearl`, which forces a ender pearl drop from enderman, regardless of the loot table.
