### ISSUE TITLE
[Mod Support] Silent Gear

### ISSUE THREAD

**Issue by oliverrook** [MarkusBordihn/BOs-Easy-Mob-Farm#52]
https://www.curseforge.com/minecraft/mc-mods/silent-gear

Based on the template, I'm guessing this is a more unusual request but:
The compatibility I'd like to suggest is having silent gear tools not break when put in a mob farm. Silent Gear tools function identical to normal tools, and even can be used by mods like mine colonies innately, however they don't break when they reach 0 durability, they just lose most of their stats. After this, they can just be repaired.

However, when you use these tools in a farm from this mod, they disappear when they reach 0 durability, resulting in you losing said tool and being unable to repair it. For lower value tools this is fine, but if you put in a more valuable weapon, say a sword with a diamond tip and iron handle so it has much more durability, it will be lost.

**Comment by MarkusBordihn** [comment]
Thanks for the report. I will not be able to implement the "silent-gear" logic 1:1 but I'm happy to implement something which helps that the items don't break.

Never played with Silent-Gear myself, but according your descriptions it sounds that items with 0 durability will just stay in their slots but will no longer be consumed, correct ?

Do you have any preference how this should work for automation. Should the item be automatically put in the output slots if it reach a durability of 0 instead of getting destroyed ?
Some like this would allow to automatically refill the weapon slot as soon the item reaches the durability 0.

**Comment by oliverrook** [comment]
That sounds like a good solution, yes.
