### ISSUE TITLE
[1.18.2] Avility to add/set what weapon/items can be placed in weapon slot

### ISSUE THREAD

**Issue by V972** [MarkusBordihn/BOs-Easy-Mob-Farm#58]
**Is your feature request related to a problem? Please describe.**
Some mobs require special wepons and/or tools to be killed with in order for some loot to drop.
Example: Farmer's delight knives allow additional/special drops, Mowzie's mob's Grottol can only be killed with pickaxe.

**Describe the solution you'd like**
Either a field in config for the farms or a tag for items that will allow them to be placed in the weapon slot.

**Describe alternatives you've considered**

**Additional context**
I'm making a modpack for 1.18.2 so I would like to see this feature on 1.18.2 version. Otherwise, there's no point in me writing this :V

**Comment by MarkusBordihn** [comment]
Thanks for the feedback. I could add support for additional weapons, but it doesn't mean that all weapons will drop the correct loot out of the box.

There are some mods and items which using custom loot tables instead of the normal loot tables so I'm unable to detect the correct loot for such items.

**Comment by MarkusBordihn** [comment]
This version no longer includes a weapon slot. Therefore, I will close this issue for now. 
If there is still a need for this functionality, please feel free to open a new feature request to explore alternative solutions.
