### ISSUE TITLE
AI Assistance in Mod Development

### ISSUE THREAD

**Issue by CrazyBobcatStudios** [MarkusBordihn/BOs-Easy-Mob-Farm#71]
Womp womp

**Comment by MarkusBordihn** [comment]
Due to a reading and writing difficulty, I use AI assistance to enhance text clarity and efficiently handle repetitive or similar code tasks. 
AI helps solve known issues, but it does not independently create full Minecraft mods. 
Some aspects of my workflow include:

- Visual Elements: Certain graphics, like logos, are created by professional artists from Fiverr. I design other elements, such as the UI, myself.
- Mob Cards: AI supports the initial generation of Mob Cards; however, I often perform further editing to refine them.

This message has also been refined with AI assistance. 

**If you find specific elements unclear or needing adjustment, please provide details, and I’ll be happy to revise accordingly.**

Below is an image that shows how I layer the UI in my graphics tool, giving insight into the design process for custom mod elements:

![image](https://github.com/user-attachments/assets/bdb87f2d-11b6-4de4-b163-004375fadbc6)
