### ISSUE TITLE
[Feature Request] Bee farm doesn't seem to do anything

### ISSUE THREAD

**Issue by munchampus** [MarkusBordihn/BOs-Easy-Mob-Farm#76]
💡 Check the
[Bug Tracker](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/issues?q=label%3Abug)
and [Crash Tracker](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/issues?q=label%3Acrash)
before
reporting a new issue.
There you can find a lot of useful information and solutions for common problems.

**Note**:
Please make sure to fill out the following template to the best of your ability. This will help us
to identify and fix the issue faster.

**Minecraft and Mod version** 🐞
1.20.1 forge 8.4.0 mod

**Describe the bug** 🐞
Puts bees in bee hive farms (tried both aggro and neutral bees) and they do not seem to drop anything (tier 2 farm with speed, quality, and exp enhancement (on a side note the exp enhancement doesn't seem to ever give exp, even on a tier 3 farm with zombie piglins)

**To Reproduce** ⚙️

**Expected behavior** ✔️

**Screenshots** 📸

**Debugging** 🛠️
Before reporting an issue, please enable the debug mode over `/easy_mob_farm debug log true` to get
more
detailed information about the issue in the logs.
Additionally, check if there is anything relevant in the crash-reports, debug.log, and latest.log
file.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)** 🧩

**Additional context** 📝

**Comment by MarkusBordihn** [comment]
Thank you for the feedback! The Easy Mob Farm relies on mob loot tables to generate corresponding drops.

In this case, bees typically don’t drop any items, so even if you kill them with a sword, arrow, lava, or water, they won’t drop anything, as their loot table is empty.

Would you be interested in a bee-specific item that could be farmed for honey or honeycombs, similar to the sheep enhancement?

Regarding the experience enhancement: bees only drop 1-3 XP orbs, which results in a low drop chance. The drop chance is set to 10%, and since only 3 orbs count, the chances are low when bees yield 0, 1, or 2 orbs.

On the other hand, Zombie Piglins consistently drop 5-12 XP orbs, with an additional 1-3 XP when they don't drop a gold sword. This makes it more likely to receive drops from them. With the latest update, however, you can adjust the drop chance in the config file to increase the drop rate if needed.
