### ISSUE TITLE
[Feature Request] Better support for larger Cataclysm mobs

### ISSUE THREAD

**Issue by Papaturts** [MarkusBordihn/BOs-Easy-Mob-Farm#81]
💡 Check the
[Bug Tracker](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/issues?q=label%3Abug)
and [Crash Tracker](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/issues?q=label%3Acrash)
before
reporting a new issue.
There you can find a lot of useful information and solutions for common problems.

**Note**:
Please make sure to fill out the following template to the best of your ability. This will help us
to identify and fix the issue faster.

**Minecraft and Mod version** 🐞
The used Minecraft and Mod version.
1.20.1
8.4.0

**Describe the bug** 🐞
Seems the Cataclysm mobs disapeared from the farms

**To Reproduce** ⚙️

1. Update Easy mob farm
2. Mobs disappear

**Expected behavior** ✔️
For the mobs to be there yet

**Screenshots** 📸

**Debugging** 🛠️
Before reporting an issue, please enable the debug mode over `/easy_mob_farm debug log true` to get
more
detailed information about the issue in the logs.
Additionally, check if there is anything relevant in the crash-reports, debug.log, and latest.log
file.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)** 🧩
Cataclysm mod

**Additional context** 📝
Were the lasso's ment to be taken away?
Seems those are the only way to capture the Cataclysm mobs?

**Comment by MarkusBordihn** [comment]
Thank you for your feedback! However, this behavior is intentional and has been clearly outlined in both the changelogs and the mod page. Here's a reminder of the key points:

---

### ⚠️ **IMPORTANT DISCLAIMER: Version 8.x Compatibility Notice** ⚠️

🚨 **Warning:** Easy Mob Farm version 8.x introduces significant changes and is **NOT backward-compatible** with previous versions. ⚠️

If you are upgrading from an older version, please note the following:

- 🛑 **Existing setups may break** and require reconfiguration.
- 🔄 **Data, items, and settings** from previous versions may no longer work as expected.
- 💾 **Backup your world** or test on a separate instance before using version 8.x in your main game!

By proceeding with version 8.x, you acknowledge that older versions cannot be migrated automatically. 
Please read the release notes carefully to avoid any issues. Happy farming! 🌾

---

As for Cataclysm mobs, they are functioning as intended but need to be **re-captured** using the new mob-catching items introduced in version 8.x.

![image](https://github.com/user-attachments/assets/7a0476de-17c6-4a65-a29a-46dd8ffca3c8)

For more details, please refer to the [MobCatcher Documentation](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/wiki/MobCatcher).

**Comment by Papaturts** [comment]
Is there a way to catch the netherite monstrosity?
To large for the Mystic Binding crystal

**Comment by MarkusBordihn** [comment]
Technically, you can use the Creative Mob Catcher to capture larger mobs, but I plan to introduce a new standard item for this purpose in the next update.

The Netherite Monstrosity has dimensions of 3.0f x 5.75f, and there are several other issues (e.g., animations, scaling, etc.) that I need to address before it will be usable.

Reference: [ModEntities.java - Line 56](https://github.com/lender544/new1.20.1/blob/e7eb15e6ed0e18c2e612fb3a075b2c288d6ee01c/src/main/java/com/github/L_Ender/cataclysm/init/ModEntities.java#L56)

**Comment by Papaturts** [comment]
Alrighty, thank you
So the mobs that are over the limit are the ones getting reworked an should be catchable in the next update?
Thank you again for your time
