### ISSUE TITLE
[Feature Request] Loot drops for 3rd party mods.

### ISSUE THREAD

**Issue by senorsmith003** [MarkusBordihn/BOs-Easy-Mob-Farm#89]
💡 Check the [Wiki](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/wiki) and
[Feature Request Tracker](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/issues?q=label%3Aenhancement)
before reporting a feature request.
There you can find a lot of useful information and solutions for common problems.

**Is your feature request related to a problem? Please describe.** 🤔
I searched the wiki and found examples of how to configure various things, but one thing i could not find was custom drops for custom mobs (such as the cobblemon mod pokemon) I saw that there was a json file to edit the bonus drops. I am assuming that is related to the mob/biome/level combination, producing bonus item drops. I am looking for something to edit what mob that are not in base minecraft data can produce while inside the farm.

**Describe the solution you'd like** 💭
I would like a way to edit the items dropped by custom mob cards when placed inside the mob farm(For example, a pikachu card will produce a pokeball when inside the farm)

**Describe alternatives you've considered** 🔄
I unfortunately I am unsure of alternative solutions, unless I simply could not find the solution
**Additional context** 📝
![image_2024-12-02_192349106](https://github.com/user-attachments/assets/7a47f859-c248-4d03-a5d5-af4bb107ddfd)
This is an image after leaving a pokemon drop card active for over 20 minutes

Thank you for your help/consideration!

**Comment by MarkusBordihn** [comment]
Thank you for your feedback! However, this behavior is intentional. The mob farm does not generate loot out of nothing; instead, it uses pre-defined loot tables to produce the corresponding loot based on specific conditions, such as "killed by player" or "killed by ...".

For mobs like those in Cobblemon and similar mods, it is generally not expected for them to drop loot, making them less suitable for use in a mob farm from a technical standpoint.

That said, you are welcome to create your own loot tables to define exactly what loot each mob should drop. For example, you can use tools like [Misode's Loot Table Generator](https://misode.github.io/loot-table/) to customize the loot drops to your liking. Any custom loot tables you create will be automatically supported by the Easy Mob Farm.

**Comment by senorsmith003** [comment]
Thank you for the response!

I figured it might be the case, with the degree of ways mobs can be
defeated, as well as with the possibilities of modded mobs and everything.

A simple datapack should suffice to make the custom changes I am guessing?

Again, thank you so much!!

**Comment by MarkusBordihn** [comment]
> A simple datapack should suffice to make the custom changes I am guessing?

Correct. A simple datapack with the corresponding loot tables for the mobs should be sufficient and offers plenty of possibilities.
For example, you can specify that certain rare drops require the mob farm "sword" (killed by sword / player) enhancement, while others do not.
